### ISSUE TITLE
Logging isn't working

### ISSUE THREAD

**Issue by jbzdarkid** [jayme-github/steamweb#10]
At least for me, in 2.7:
Doesn't get printed to stdin. If I specify a file with Logger.basicConfig(filename="debug.log"), the logfile remains empty during execution.

**Comment by jayme-github** [comment]
You'll probably have to set a appropriate loglevel (like `level=logging.DEBUG`).
Please take a look at what [demo.py](https://github.com/jayme-github/steamweb/blob/master/demo.py) does.
