### ISSUE TITLE
Captcha Service Support

### ISSUE THREAD

**Issue by articlefr** [jayme-github/steamweb#13]
Hi,

I'd like to ask support for integration of https://www.captchasolutions.com captcha solving service which supports all captchas of steampowered website.

Thanks!

**Comment by jayme-github** [comment]
Would be a nice addition indeed. Can you provide a sponsored account for integration and testing (not shared of cause!)?

**Comment by articlefr** [comment]
Just register an account and you'll be given 10 tokens automatically for free and should be enough for testing purposes. Thank you.
